name: PR Build

on:
  pull_request:
    branches: [ dev ]
env:  
  DOTNET_CLI_TELEMETRY_OPTOUT: '1'
  
jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'   

    - name: Install dependencies
      run: dotnet build ./src/Theraparea.HttpApi.Host/Theraparea.HttpApi.Host.csproj  
    
    - name: Unit Test
      run: |
        dotnet tool install dotnet-coverage
        dotnet tool run dotnet-coverage collect -f cobertura -o Theraparea.Application dotnet test ./test/Theraparea.Application.Tests/Theraparea.Application.Tests.csproj        
        dotnet tool run dotnet-coverage collect -f cobertura -o Theraparea.Domain dotnet test ./test/Theraparea.Domain.Tests/Theraparea.Domain.Tests.csproj        
        dotnet tool run dotnet-coverage collect -f cobertura -o Theraparea.EntityFrameworkCore dotnet test ./test/Theraparea.EntityFrameworkCore.Tests/Theraparea.EntityFrameworkCore.Tests.csproj
        dotnet tool run dotnet-coverage merge --remove-input-files -o ${{github.workspace}}/coverage.xml -f cobertura -r *.cobertura.xml        
        
    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos 
        directory: ${{github.workspace}}
        files: ./coverage.xml # optional
        flags: unittests # optional
        name: codecov-theraparea # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)