name: Static Site Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use nodejs 
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Npm Install
        run: npm ci --force
        
      - name: Build
        run: npm run build --if-present
      - name: Test 
        run: npm test
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy Site
        run: |
          aws s3 cp dist/apps/theraparea.client/ s3://${{ secrets.BUCKET_NAME }}/$GITHUB_REF_NAME --recursive --exclude "*" --include "*.html" --cache-control "no-cache" --content-type "text/html"
          aws s3 cp dist/apps/theraparea.client/ s3://${{ secrets.BUCKET_NAME }}/$GITHUB_REF_NAME --recursive --exclude "*" --include "*.js" --cache-control "public; max-age=2592000" --content-type "application/javascript"
          aws s3 cp dist/apps/theraparea.client/ s3://${{ secrets.BUCKET_NAME }}/$GITHUB_REF_NAME --recursive --exclude "*" --include "*.ico" --cache-control "public; max-age=2592000" --content-type "image/x-icon"
          aws s3 cp dist/apps/theraparea.client/ s3://${{ secrets.BUCKET_NAME }}/$GITHUB_REF_NAME --recursive --exclude "*" --include "*.png" --cache-control "public; max-age=2592000" --content-type "image/png"
          aws s3 cp dist/apps/theraparea.client/ s3://${{ secrets.BUCKET_NAME }}/$GITHUB_REF_NAME --recursive --exclude "*" --include "*.json" --cache-control "no-cache" --content-type "application/json"
          aws s3 cp dist/apps/theraparea.client/ s3://${{ secrets.BUCKET_NAME }}/$GITHUB_REF_NAME --recursive --exclude "*" --include "*.css" --cache-control "public; max-age=2592000" --content-type "text/css"
